stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build --network=host -t registry2023.skyshi.io/document-asker-bot/api-gateway:$CI_COMMIT_SHA .
    - docker push registry2023.skyshi.io/document-asker-bot/api-gateway:$CI_COMMIT_SHA
  only:
    - main

build_prod:
  stage: build
  script:
    - docker build --network=host -t registry2023.skyshi.io/document-asker-bot/api-gateway:$CI_COMMIT_SHA .
    - docker push registry2023.skyshi.io/document-asker-bot/api-gateway:$CI_COMMIT_SHA
  only:
    - prod

deploy:
  stage: deploy
  image: registry2023.skyshi.io/rancher-deploy:latest
  variables:
    STACK_NAME: document-asker-bot
    RANCHER_ACCESS_KEY: 7883945FF628446F34F6
    RANCHER_ENVIRONMENT: staging
    RANCHER_SECRET_KEY: HpMvXcp7ZmbrWEw9K1wazk6e2pbJ6TCT3wiLL37m
    RANCHER_URL: https://rancher.skyshi.io/v1
  script:
    - ''

  only:
    - main
